name: feature_counts_qc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # TODO nf-core: Add required software dependencies here
  - conda-forge::r-dplyr=0.8.0.1
  - conda-forge::r-optparse=1.6.1
  - conda-forge::r-plotly=4.8.0
  - conda-forge::r-data.table=1.12.2
  - conda-forge::r-roxygen2=6.1.1
  - conda-forge::r-readr=1.3.1
  - conda-forge::r-htmlwidgets=1.3
  - conda-forge::pandoc=2.7.2
  - bioconda::bioconductor-summarizedexperiment=1.12.0
  - bioconda::bioconductor-cqn=1.28.1
  - r::r-devtools=1.13.6

